# Generated by Django 5.1.3 on 2024-11-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(db_column='Staff_Name', max_length=35)),
                ('designation', models.CharField(choices=[('HOD', 'Head of Department'), ('STAFF/AP', 'Staff/AP'), ('STAFF/ASP', 'Staff/ASP'), ('LAB INCHARGE', 'Lab Incharge'), ('COE', 'Controller of Examinations'), ('PRINCIPAL', 'Principal'), ('ADMIN', 'Administrator')], db_column='designation', max_length=20)),
                ('department', models.CharField(blank=True, db_column='department', max_length=10, null=True)),
                ('handling_subject', models.CharField(blank=True, db_column='Handling_Subject', max_length=35, null=True)),
                ('flag_f', models.CharField(choices=[('x', 'Inactive'), ('o', 'Active')], db_column='flagF', default='o', max_length=1)),
                ('date_of_joining', models.DateField(db_column='Date_of_joining')),
                ('institution_name', models.CharField(choices=[('PAAVAI ENGINEERING COLLEGE', 'Paavai Engineering College'), ('PAAVAI COLLEGE OF ENGINEERING', 'Paavai College of Engineering')], db_column='instution_name', max_length=30)),
                ('institution_number', models.CharField(choices=[('6221', '6221'), ('6220', '6220')], db_column='instution_number', max_length=4)),
            ],
            options={
                'db_table': 'faculty',
                'managed': False,
            },
        ),
    ]
