# Generated by Django 5.1.3 on 2024-11-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance2226', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyLogin',
            fields=[
                ('name', models.CharField(max_length=35)),
                ('username', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'faculty_login',
                'managed': False,
            },
        ),
    ]
