# Generated by Django 5.1.3 on 2024-11-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance2226', '0002_facultylogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudMetaData',
            fields=[
                ('REG_NO', models.BigIntegerField(primary_key=True, serialize=False)),
                ('stud_name', models.CharField(max_length=50)),
                ('college_name', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=10)),
                ('stud_dept', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('section', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=10)),
                ('join_year', models.IntegerField()),
                ('passout_year', models.IntegerField()),
            ],
            options={
                'db_table': 'stud_meta_data',
            },
        ),
    ]
