# Generated by Django 5.1.3 on 2024-12-14 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance2226', '0003_studmetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourTable',
            fields=[
                ('hour_id', models.AutoField(primary_key=True, serialize=False)),  # Explicit primary key
                ('at_year', models.IntegerField()),
                ('at_dept', models.CharField(max_length=35)),
                ('at_day_order', models.IntegerField()),
                ('sub1', models.CharField(max_length=50)),
                ('sub2', models.CharField(max_length=50)),
                ('sub3', models.CharField(max_length=50)),
                ('sub4', models.CharField(max_length=50)),
                ('sub5', models.CharField(max_length=50)),
                ('sub6', models.CharField(max_length=50)),
                ('sub7', models.CharField(max_length=50)),
                ('at_sdate', models.DateField()),
                ('at_edate', models.DateField()),
            ],
            options={
                'db_table': 'hour_table',
            },
        ),
        migrations.CreateModel(
            name='AttendanceEntry',
            fields=[
                ('attend_id', models.AutoField(primary_key=True, serialize=False)),  # Explicit primary key
                ('college_name', models.CharField(max_length=50)),
                ('stud_dept', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('section', models.CharField(max_length=5)),
                ('attend_date', models.DateField()),
                ('day_order', models.IntegerField()),
                ('hour_1', models.CharField(choices=[('1', 'Present'), ('0', 'Absent'), ('OD', 'On Duty')], max_length=2)),
                ('hour_2', models.CharField(choices=[('1', 'Present'), ('0', 'Absent'), ('OD', 'On Duty')], max_length=2)),
                ('hour_3', models.CharField(choices=[('1', 'Present'), ('0', 'Absent'), ('OD', 'On Duty')], max_length=2)),
                ('hour_4', models.CharField(choices=[('1', 'Present'), ('0', 'Absent'), ('OD', 'On Duty')], max_length=2)),
                ('hour_5', models.CharField(choices=[('1', 'Present'), ('0', 'Absent'), ('OD', 'On Duty')], max_length=2)),
                ('hour_6', models.CharField(choices=[('1', 'Present'), ('0', 'Absent'), ('OD', 'On Duty')], max_length=2)),
                ('hour_7', models.CharField(choices=[('1', 'Present'), ('0', 'Absent'), ('OD', 'On Duty')], max_length=2)),
                ('sdate', models.DateField()),
                ('edate', models.DateField()),
                ('stud_meta_data', models.ForeignKey(
                    db_column='REG_NO',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='attendance_entries',
                    to='attendance2226.studmetadata',
                )),
                ('hour_table', models.ForeignKey(
                    db_column='hour_id',  # Reference hour_id
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='attendance_entries',
                    to='attendance2226.hourtable',
                )),
            ],
            options={
                'db_table': 'attendance_entry',
            },
        ),
    ]
