# Generated by Django 5.1.3 on 2024-12-14 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance2226', '0004_hourtable_attendanceentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceentry',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='hourtable',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='studmetadata',
            options={'managed': False},
        ),
    ]
