# Generated by Django 5.1.3 on 2025-01-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance2226', '0005_alter_attendanceentry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectHandle',
            fields=[
                ('sh_id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('day_order', models.PositiveIntegerField()),
                ('hour', models.PositiveIntegerField()),
                ('mode_of_handle', models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical'), ('others', 'Others')], max_length=10)),
                ('sdate', models.DateField()),
                ('edate', models.DateField()),
            ],
            options={
                'db_table': 'subject_handle',
                'managed': False,
            },
        ),
    ]
